extends SceneTree


func _fail(message: String) -> void:
	push_error(message)
	quit(1)


func _init() -> void:
	var source := FileAccess.get_file_as_string("res://scripts/main.gd")
	if source.is_empty():
		_fail("Unable to read main.gd.")
		return
	var required := [
		"scripts/state/game_state_store.gd",
		"scripts/state/dirty_graph.gd",
		"scripts/state/derived_state_cache.gd",
		"scripts/perf/hot_path_profiler.gd",
		"scripts/services/gpu_geometry_service.gd",
		"scripts/services/training_entry_service.gd",
		"scripts/services/saved_unit_library_service.gd",
		"scripts/services/battle_input_service.gd",
		"scripts/services/battle_frame_orchestrator_service.gd",
		"scripts/services/battle_presentation_frame_service.gd",
		"scripts/battle/battle_runtime_facade.gd",
		"scripts/battle/battle_presentation_host_adapter.gd",
		"scripts/battle/battle_presentation_applier.gd",
		"scripts/services/battle_actor_command_service.gd",
		"scripts/services/battle_field_runtime_service.gd",
		"scripts/services/battle_hit_resolution_service.gd",
		"scripts/services/battle_projectile_lifecycle_service.gd",
		"scripts/services/battle_action_event_service.gd",
		"scripts/services/battle_impact_query_service.gd",
		"scripts/services/battle_identity_runtime_service.gd",
		"scripts/services/battle_spatial_runtime_service.gd",
		"scripts/services/battle_map_occlusion_service.gd",
		"scripts/services/battle_target_acquisition_service.gd",
		"scripts/services/projectile_runtime_service.gd",
		"scripts/services/runtime_contact_service.gd",
		"scripts/services/runtime_collider_geometry_service.gd",
		"scripts/services/battle_vfx_budget_service.gd",
		"scripts/services/battle_runtime_lifecycle_service.gd",
		"scripts/services/battle_hud_state_service.gd",
		"scripts/services/battle_awareness_service.gd",
		"scripts/services/battle_runtime_action_telemetry_service.gd",
		"scripts/views/battle_action_diagnostics_view.gd",
		"scripts/controllers/team_edit_controller.gd",
		"scripts/controllers/saved_units_controller.gd",
		"scripts/controllers/unit_editor_catalog_controller.gd",
		"scripts/controllers/unit_editor_board_controller.gd",
		"scripts/controllers/battle_controller.gd",
		"SavedUnitsController.new",
		"saved_units_controller.filter_entries",
		"saved_units_controller.selection_state_for_card",
		"saved_units_controller.hover_state_for_card",
		"saved_units_controller.delete_request_intent",
		"saved_units_controller.page_action_state",
		"TrainingEntryService.new",
		"func _training_entry_service() -> TrainingEntryService",
		"_training_entry_service().ball_stats",
		"_training_entry_service().pending_imports",
		"_training_entry_service().loadout_from_imports",
		"_training_entry_service().first_legal_hero_entry",
		"_training_entry_service().starter_loadout",
		"_training_entry_service().training_side_assignment",
		"SavedUnitLibraryService.new",
		"func _saved_unit_library_service() -> SavedUnitLibraryService",
		"_saved_unit_library_service().signature_from_records",
		"_saved_unit_library_service().cache_refresh_intent",
		"_saved_unit_library_service().build_save_payload",
		"_saved_unit_library_service().entry_from_payload",
		"_saved_unit_library_service().rejected_entry_from_payload",
		"_saved_unit_library_service().entries_from_records",
		"BattleInputService.new",
		"func _battle_input_service() -> BattleInputService",
		"_battle_input_service().battle_action_names",
		"_battle_input_service().capture_edge_frame",
		"_battle_input_service().consume_edges_once",
		"_battle_input_service().action_just_pressed",
		"_battle_input_service().action_just_released",
		"_battle_input_service().battle_control_routes",
		"_battle_input_service().direction_just_pressed",
		"_battle_input_service().movement_input_state",
		"_battle_input_service().spectator_input_intent",
		"BattleFrameOrchestratorService.new",
		"func _battle_frame_orchestrator_service() -> BattleFrameOrchestratorService",
		"BattleRuntimeFacade.new",
		"func _battle_runtime_facade() -> BattleRuntimeFacade",
		"_battle_runtime_facade().frame_step_plan",
		"_battle_runtime_facade().simulation_phase_plan",
		"_battle_runtime_facade().contact_pass_plan",
		"_battle_runtime_facade().post_step_state",
		"BattlePresentationFrameService.new",
		"func _battle_presentation_frame_service() -> BattlePresentationFrameService",
		"battle_runtime_facade.bind_presentation_frame(battle_presentation_frame_service)",
		"_battle_runtime_facade().motion_snapshot_state",
		"_battle_runtime_facade().render_frame_plan",
		"_battle_camera_snapshot_state",
		"_apply_battle_camera_snapshot_state",
		"BattlePresentationHostAdapter.new",
		"func _battle_presentation_host_adapter() -> BattlePresentationHostAdapter",
		"func _battle_presentation_host_callbacks() -> Dictionary",
		"Callable(self, \"_refresh_mobius_surface_view\")",
		"BattlePresentationApplier.new",
		"func _battle_presentation_applier() -> BattlePresentationApplier",
		"_battle_presentation_applier().apply_render_frame",
		"_battle_presentation_applier().apply_render_frame(_battle_presentation_host_adapter(), plan)",
		"BattleActorCommandService.new",
		"_battle_actor_command_service().deploy_tick_plan",
		"_battle_actor_command_service().summon_gate_intent",
		"_battle_actor_command_service().auto_summon_intent",
		"_battle_actor_command_service().puppet_condition",
		"_battle_actor_command_service().puppet_move_intent",
		"_battle_actor_command_service().puppet_attack_intent",
		"_battle_actor_command_service().barrier_logic_intents",
		"_battle_actor_command_service().command_diagnostics",
		"BattleFieldRuntimeService.new",
		"_battle_field_runtime_service().lease_intent",
		"_battle_field_runtime_service().annuity_intent",
		"_battle_field_runtime_service().support_aura_model",
		"_battle_field_runtime_service().support_target_intent",
		"_battle_field_runtime_service().speed_lane_intent",
		"_battle_field_runtime_service().coin_generator_intent",
		"_battle_field_runtime_service().field_coin_update_intent",
		"_battle_field_runtime_service().signal_jammer_intent",
		"_battle_field_runtime_service().barrier_utility_intents",
		"_battle_field_runtime_service().field_effect_intent",
		"_battle_field_runtime_service().trap_trigger_intent",
		"_battle_field_runtime_service().trap_fire_intents",
		"_battle_field_runtime_service().hatchery_intent",
		"_battle_field_runtime_service().hatchling_stats_intent",
		"BattleHitResolutionService.new",
		"_battle_hit_resolution_service().attack_entry_intent",
		"_battle_hit_resolution_service().projectile_preflight_intent",
		"_battle_hit_resolution_service().target_hit_context",
		"_battle_hit_resolution_service().combo_scaling_intent",
		"_battle_hit_resolution_service().damage_stack_intent",
		"_battle_hit_resolution_service().part_damage_intent",
		"_battle_hit_resolution_service().momentum_response_intent",
		"_battle_hit_resolution_service().post_hit_intents",
		"_battle_hit_resolution_service().status_tick_intent",
		"BattleProjectileLifecycleService.new",
		"_battle_projectile_lifecycle_service().chemical_projectile_tick_intent",
		"_battle_projectile_lifecycle_service().missile_projectile_tick_intent",
		"_battle_projectile_lifecycle_service().chemical_firework_pellet_intents",
		"_battle_projectile_lifecycle_service().web_tether_tick_intent",
		"_battle_projectile_lifecycle_service().web_swing_tick_intent",
		"_battle_projectile_lifecycle_service().web_target_candidate_intent",
		"_battle_projectile_lifecycle_service().web_impact_candidate_intent",
		"_battle_projectile_lifecycle_service().web_impact_selection",
		"_battle_projectile_lifecycle_service().web_boundary_anchor_intent",
		"_battle_projectile_lifecycle_service().web_fire_intent",
		"_battle_projectile_lifecycle_service().explosion_damage_intent",
		"_battle_projectile_lifecycle_service().projectile_reflection_intent",
		"_battle_projectile_lifecycle_service().target_shield_reflection_intent",
		"BattleActionEventService.new",
		"_battle_action_event_service().begin_module_action_intent",
		"_battle_action_event_service().gun_activation_event_patch",
		"_battle_action_event_service().module_event_patch",
		"_battle_action_event_service().runtime_direct_module_event_patch",
		"_battle_action_event_service().command_window_route_intent",
		"_battle_action_event_service().control_event_fields_patch",
		"_battle_action_event_service().module_variant_event_patch",
		"_battle_action_event_service().module_effect_event_patch",
		"BattleImpactQueryService.new",
		"_battle_impact_query_service().projectile_direction_intent",
		"_battle_impact_query_service().projectile_candidate_intent",
		"_battle_impact_query_service().first_impact_selection",
		"_battle_impact_query_service().gpu_hit_selection",
		"_battle_impact_query_service().hit_slop_intent",
		"_battle_impact_query_service().part_hit_candidate_intent",
		"_battle_impact_query_service().part_hit_payload",
		"BattleIdentityRuntimeService.new",
		"_battle_identity_runtime_service().role_switch_gate_intent",
		"_battle_identity_runtime_service().soul_cast_gate_intent",
		"_battle_identity_runtime_service().identity_receiver_selection",
		"_battle_identity_runtime_service().role_switch_target_selection",
		"_battle_identity_runtime_service().identity_transfer_plan",
		"_battle_identity_runtime_service().role_form_target",
		"_battle_identity_runtime_service().role_form_gate_intent",
		"_battle_identity_runtime_service().role_form_finish_intent",
		"_battle_identity_runtime_service().morph_intent",
		"_battle_identity_runtime_service().morph_shape_for_mode",
		"_battle_identity_runtime_service().combine_partner_selection",
		"_battle_identity_runtime_service().combine_intent",
		"_battle_identity_runtime_service().separate_intent",
		"_battle_identity_runtime_service().separated_partner_spawn_intent",
		"BattleSpatialRuntimeService.new",
		"_battle_spatial_runtime_service().camera_follow_alpha",
		"_battle_spatial_runtime_service().player_camera_focus_intent",
		"_battle_spatial_runtime_service().spectator_camera_focus_intent",
		"_battle_spatial_runtime_service().camera_update_intent",
		"_battle_spatial_runtime_service().screen_projection_intent",
		"_battle_spatial_runtime_service().world_point_visibility_intent",
		"_battle_spatial_runtime_service().portal_spawn_intent",
		"_battle_spatial_runtime_service().surface_input_intent",
		"BattleMapOcclusionService.new",
		"_battle_map_occlusion_service().occlusion_kind_for_data",
		"_battle_map_occlusion_service().path_collider_for_event",
		"_battle_map_occlusion_service().path_collider_between",
		"_battle_map_occlusion_service().blocker_candidate_intent",
		"_battle_map_occlusion_service().occlusion_query_from_candidates",
		"_battle_map_occlusion_service().occlusion_kind_from_query",
		"_battle_map_occlusion_service().line_occluded",
		"_battle_map_occlusion_service().line_of_sight_clear",
		"BattleTargetAcquisitionService.new",
		"_battle_target_acquisition_service().normalized_target_direction",
		"_battle_target_acquisition_service().target_class",
		"_battle_target_acquisition_service().target_class_allowed",
		"_battle_target_acquisition_service().true_bullet_candidate_intent",
		"_battle_target_acquisition_service().true_bullet_target_selection",
		"_battle_target_acquisition_service().missile_candidate_intent",
		"_battle_target_acquisition_service().missile_lock_score",
		"_battle_target_acquisition_service().missile_target_selection",
		"ProjectileRuntimeService.new",
		"_projectile_runtime_service().projectile_behavior_for_data",
		"_projectile_runtime_service().projectile_behavior_key",
		"_projectile_runtime_service().projectile_collision_speed_for_event",
		"_projectile_runtime_service().projectile_mass_for_event",
		"_projectile_runtime_service().projectile_momentum_state_for_event",
		"_projectile_runtime_service().gun_projectile_damage_mult_max_for_data",
		"_projectile_runtime_service().projectile_damage_coeffs_for_event",
		"_projectile_runtime_service().projectile_raw_damage_for_momentum",
		"_projectile_runtime_service().heat_tags_for_projectile_event",
		"_projectile_runtime_service().chemical_queue_intent",
		"_projectile_runtime_service().missile_queue_intent",
		"_projectile_runtime_service().web_trace_event",
		"_projectile_runtime_service().trace_payload",
		"RuntimeContactService.new",
		"_runtime_contact_service().socket_key",
		"_runtime_contact_service().sorted_colliders",
		"_runtime_contact_service().collider_priority",
		"_runtime_contact_service().pair_key",
		"_runtime_contact_service().directed_contact_key",
		"_runtime_contact_service().damage_coeff",
		"_runtime_contact_service().break_coeff",
		"_runtime_contact_service().part_stiffness",
		"_runtime_contact_service().path_stiffness",
		"_runtime_contact_service().break_threshold",
		"_runtime_contact_service().damage_type",
		"_runtime_contact_service().material_class",
		"_runtime_contact_service().runtime_pair_intent",
		"_runtime_contact_service().gpu_contact_intent",
		"_runtime_contact_service().damage_intent",
		"_runtime_contact_service().velocity_response_intent",
		"_runtime_contact_service().runtime_recovery_capable",
		"_runtime_contact_service().runtime_action_phase",
		"_runtime_contact_service().passive_contact_scrape_factor",
		"_runtime_contact_service().passive_contact_damage_key",
		"_runtime_contact_service().unit_contact_radius",
		"_runtime_contact_service().unit_effective_mass",
		"_runtime_contact_service().unit_thruster_power",
		"_runtime_contact_service().unit_knockback_resist",
		"_runtime_contact_service().unit_impulse_motion_mult",
		"_runtime_contact_service().unit_melee_stability_threshold",
		"_runtime_contact_service().unit_posture_anchor",
		"RuntimeColliderGeometryService.new",
		"_runtime_collider_geometry_service().collider_gap",
		"_runtime_collider_geometry_service().scale_collider_around_center",
		"BattleVfxBudgetService.new",
		"battle_vfx_budget_service.reset_frame_state",
		"battle_vfx_budget_service.consume_code",
		"BattleRuntimeLifecycleService.new",
		"battle_runtime_facade.bind_runtime_lifecycle(battle_runtime_lifecycle_service)",
		"_battle_runtime_facade().cleanup_intent",
		"_battle_runtime_facade().snapshot_summary",
		"_battle_runtime_facade().kill_flow_intent",
		"_battle_runtime_facade().destroy_economy_intents",
		"_battle_runtime_facade().pirate_betrayal_intent",
		"_battle_runtime_facade().retreat_start_intent",
		"_battle_runtime_facade().retreat_repair_tick_intent",
		"_battle_runtime_facade().escape_pod_spawn_intent",
		"_battle_runtime_facade().escape_pod_tick_intent",
		"_battle_runtime_facade().fracture_cleanup_intent",
		"_battle_runtime_facade().torso_fracture_brood_intent",
		"BattleHudStateService.new",
		"func _battle_hud_service() -> BattleHudStateService",
		"_battle_hud_service().heavy_hud_text_state",
		"_battle_hud_service().heavy_hud_bar_state",
		"_battle_hud_service().corner_bar_model",
		"_battle_hud_service().instrument_gauge_model",
		"_battle_hud_service().role_status_text",
		"_battle_hud_service().role_bar_text",
		"_battle_hud_service().ammo_display_text",
		"BattleAwarenessService.new",
		"battle_awareness_service.minimap_world_model",
		"battle_awareness_service.enemy_ids",
		"battle_awareness_service.friendly_ids",
		"battle_awareness_service.nearest_candidate_id",
		"battle_awareness_service.source_target_intent",
		"battle_awareness_service.source_target_score",
		"BattleRuntimeActionTelemetryService.new",
		"battle_runtime_facade.bind_action_telemetry(battle_runtime_action_telemetry_service)",
		"_battle_runtime_facade().battle_action_telemetry",
		"_battle_runtime_facade().battle_action_diagnostics_model",
		"_battle_runtime_facade().projectile_target_diagnostics",
		"_battle_runtime_action_telemetry_snapshot",
		"_battle_command_diagnostics_unit_snapshot",
		"_battle_command_diagnostics_source_rule",
		"_set_battle_action_diagnostics_overlay_enabled",
		"_battle_action_diagnostics_overlay_text",
		"_update_battle_action_diagnostics_overlay",
		"_battle_action_diagnostics_model",
		"UnitEditorCatalogController.new",
		"UnitEditorBoardController.new",
		"unit_editor_board_controller.route_board_input_event",
		"func _initialize_hot_path_state_layer",
	]
	for token in required:
		if not source.contains(token):
			_fail("main.gd is missing controller/state adapter token: %s" % token)
			return
	if source.contains("team_edit_controller = null") or source.contains("battle_controller = null"):
		_fail("Controller adapters are explicitly disabled.")
		return
	var board_input_body := _function_body(source, "func _handle_editor_board_input")
	if board_input_body.is_empty():
		_fail("Unable to locate _handle_editor_board_input body.")
		return
	for forbidden in [
		"if event is InputEventMouseMotion",
		"if editor_pose_dragging and",
		"elif editor_selecting_topology_box",
		"elif editor_dragging_node_index",
		"elif editor_dragging_whole_unit",
		"if mouse_event.pressed and",
		"if not mouse_event.pressed",
		"_try_magnetic_link_for_node(unit_bp, editor_dragging_node_index)",
		"_handle_barrier_board_click(mouse_event, unit_bp)",
		"_board_part_at(mouse_event.position)",
	]:
		if board_input_body.contains(forbidden):
			_fail("_handle_editor_board_input should be controller-only; found fallback token: %s" % forbidden)
			return
	for required_board_token in [
		"unit_editor_board_controller == null",
		"editor_board_controller_missing_warned",
		"push_warning",
		"_editor_board_input_context",
		"unit_editor_board_controller.route_board_input_event",
		"_dispatch_editor_board_input_route",
	]:
		if not board_input_body.contains(required_board_token):
			_fail("_handle_editor_board_input missing controller-only token: %s" % required_board_token)
			return
	print("MAIN_CONTROLLER_BOUNDARY_PROBE ok")
	quit(0)


func _function_body(source: String, signature: String) -> String:
	var start := source.find(signature)
	if start < 0:
		return ""
	var next := source.find("\nfunc ", start + signature.length())
	if next < 0:
		return source.substr(start)
	return source.substr(start, next - start)
